import { Inter } from "next/font/google";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import AppFooter from "@/components/global/AppFooter";
import AppHeader from "@/components/global/AppHeader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Next + Express Demo",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
};

export default RootLayout;
