import { Inter } from "next/font/google";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import AppFooter from "@/components/AppFooter";
import AppHeader from "@/components/AppHeader";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Next + Express Demo",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <AppHeader />
          {children}
          <AppFooter />
        </body>
      </AuthProvider>
    </html>
  );
};

export default RootLayout;
